spring: 
 profiles: 
  active: 
  - dev
  
---
spring: 
 profiles: dev
 application:
  name: microservicecloud-config-client

eureka:
 client:
  server-url: 
   defaultZone: http://eureka7001.com:7001/eureka/
   
---
spring: 
 profiles: test
 application:
  name: microservicecloud-config-client

eureka:
 client:
  server-url: 
   defaultZone: http://eureka7001.com:7001/eureka/


